import { Inter } from "next/font/google";
import "./globals.css";
import Topbar from "@/components/layout/Topbar";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

// Inter font initialize karo
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter", 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="antialiased font-inter">
        <Topbar />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
